### ISSUE TITLE
Source code of service and models

### ISSUE THREAD

**Issue by NaqiNick** [salev/tree#1]
Hello dear contributor this is some great work you've done here i'm really Thankful to you for sharing such a solution. "THANK YOU" , I'm trying to replicate what you've achieved here but while i'm trying to do that I'm stuck with the service calls when i call the service and then ".map" on the return it gives me and error saying "Property 'map' does not exist on type 'Observable<Object>'" can you please share the source code of your service and models so that I may be able to achieve what you've shared here. Thank you

**Comment by salev** [comment]
Hello!

I suppose that the problem is that my code was made for previous RxJs
version. So calling of map operator should be inside a pipe.

16:45, пт, 20.09.2019 NaqiNick notifications@github.com:

**Comment by NaqiNick** [comment]
Hi,
Sorry i'm disturbing you again but could you please help me a bit here, I've tried map inside pipe but as in the example we've used nested map the 2nd map inside the first map is now giving an error that says "Property 'map' does not exist on type 'Object'". 

This is the code:
`this.treeService.fetchUsers().pipe(
      map(users => users.map(user => new Leaf('name', new User(user), true, 'fa-user'))
      ))
      .subscribe(
        (leaves) => {
          this.tree.insertLeaves(leaves);
        },
        () => alert('error')
      );`

its giving the error on users.map could you help me with this please

**Comment by salev** [comment]
Are you sure that users is an array?

21:38, сб, 21.09.2019 NaqiNick notifications@github.com:

**Comment by NaqiNick** [comment]
Yep it wasn't an array that was the problem, Thank you Salev for you help

**Comment by salev** [comment]
Good luck. Be in touch.

14:44, чт, 26.09.2019 NaqiNick notifications@github.com:
